### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by rbstrachan** [Knewton/Zoidberg#1]
You may want to leave a link to where this can be downloaded, thanks.

**Comment by garside** [comment]
Sorry, A link to download what? I'm not quite sure what are you referring to.

**Comment by astubbs** [comment]
I think he's talking about a packaged distribution, as opposed to the source code?

**Comment by garside** [comment]
Ahhh! I never even thought about that. Something for next week I guess!

On Wed, Oct 1, 2014 at 9:22 AM, Antony Stubbs notifications@github.com
wrote:

> I think he's talking about a packaged distribution, as opposed to the
> source code?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Knewton/Zoidberg/issues/1#issuecomment-57461831.

## 

Eric Garside
Coffee Specialist
http://www.ringingtelephone.com/

**Comment by rbstrachan** [comment]
Sorry, I didnt leave enough detail. Yeah astubbs is correct, thanks!
